# Generated by Django 3.2 on 2023-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название урока')),
                ('video_link', models.URLField()),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='Длительность в секундах')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='LessonAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Время просмотра в секундах')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('last_viewed_time', models.DateTimeField(auto_now=True, verbose_name='Дата просмотра')),
            ],
            options={
                'verbose_name': 'просмотры уроков',
                'verbose_name_plural': 'просмотры уроков',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
